/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'status' : AppointmentStatus,
  'doctorId' : bigint,
  'patientId' : Principal,
  'appointmentType' : AppointmentType,
  'hospitalId' : bigint,
  'notes' : string,
  'dateTime' : string,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type AppointmentType = { 'diagnostic' : null } |
  { 'consultation' : null };
export interface CommunityEvent {
  'id' : bigint,
  'organizer' : string,
  'title' : string,
  'description' : string,
  'dateTime' : string,
  'location' : string,
  'eventType' : EventType,
}
export interface DoctorProfile {
  'id' : bigint,
  'bio' : string,
  'verified' : boolean,
  'name' : string,
  'available' : boolean,
  'specialty' : string,
  'credentials' : string,
  'hospitalId' : bigint,
  'rating' : bigint,
  'reviewCount' : bigint,
  'consultationFee' : bigint,
}
export type EventType = { 'webinar' : null } |
  { 'nutritionTour' : null } |
  { 'popupClinic' : null };
export interface Hospital {
  'id' : bigint,
  'erWaitMinutes' : bigint,
  'featuredDepartment' : string,
  'departments' : Array<string>,
  'isSponsored' : boolean,
  'name' : string,
  'description' : string,
  'address' : string,
  'rating' : bigint,
  'reviewCount' : bigint,
}
export interface Review {
  'id' : bigint,
  'authorId' : Principal,
  'comment' : string,
  'timestamp' : bigint,
  'targetType' : ReviewTargetType,
  'rating' : bigint,
  'targetId' : bigint,
}
export type ReviewTargetType = { 'hospital' : null } |
  { 'doctor' : null };
export interface UserProfile {
  'name' : string,
  'role' : string,
  'associatedId' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<[Review], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignDoctorOwner' : ActorMethod<[bigint, Principal], undefined>,
  'assignHospitalOwner' : ActorMethod<[bigint, Principal], undefined>,
  'bookAppointment' : ActorMethod<[Appointment], bigint>,
  'createDoctorProfile' : ActorMethod<[DoctorProfile], bigint>,
  'createEvent' : ActorMethod<[CommunityEvent], bigint>,
  'createHospital' : ActorMethod<[Hospital], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDoctor' : ActorMethod<[bigint], DoctorProfile>,
  'getDoctorAppointments' : ActorMethod<[bigint], Array<Appointment>>,
  'getDoctorsBySpecialty' : ActorMethod<[string], Array<DoctorProfile>>,
  'getEvent' : ActorMethod<[bigint], CommunityEvent>,
  'getEventsByType' : ActorMethod<[EventType], Array<CommunityEvent>>,
  'getHospital' : ActorMethod<[bigint], Hospital>,
  'getHospitalsByDepartment' : ActorMethod<[string], Array<Hospital>>,
  'getMatchingSpecialties' : ActorMethod<[string], Array<string>>,
  'getPatientAppointments' : ActorMethod<[Principal], Array<Appointment>>,
  'getReviewsByTarget' : ActorMethod<[bigint, ReviewTargetType], Array<Review>>,
  'getTopRatedDoctors' : ActorMethod<[], Array<DoctorProfile>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchDoctors' : ActorMethod<[string], Array<DoctorProfile>>,
  'searchHospitals' : ActorMethod<[string], Array<Hospital>>,
  'updateAppointmentStatus' : ActorMethod<
    [bigint, AppointmentStatus],
    undefined
  >,
  'updateDoctorProfile' : ActorMethod<[bigint, DoctorProfile], undefined>,
  'updateErWaitTime' : ActorMethod<[bigint, bigint], undefined>,
  'updateHospital' : ActorMethod<[bigint, Hospital], undefined>,
  'verifyDoctor' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];