/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ReviewTargetType = IDL.Variant({
  'hospital' : IDL.Null,
  'doctor' : IDL.Null,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'authorId' : IDL.Principal,
  'comment' : IDL.Text,
  'timestamp' : IDL.Int,
  'targetType' : ReviewTargetType,
  'rating' : IDL.Nat,
  'targetId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const AppointmentType = IDL.Variant({
  'diagnostic' : IDL.Null,
  'consultation' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : AppointmentStatus,
  'doctorId' : IDL.Nat,
  'patientId' : IDL.Principal,
  'appointmentType' : AppointmentType,
  'hospitalId' : IDL.Nat,
  'notes' : IDL.Text,
  'dateTime' : IDL.Text,
});
export const DoctorProfile = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'verified' : IDL.Bool,
  'name' : IDL.Text,
  'available' : IDL.Bool,
  'specialty' : IDL.Text,
  'credentials' : IDL.Text,
  'hospitalId' : IDL.Nat,
  'rating' : IDL.Nat,
  'reviewCount' : IDL.Nat,
  'consultationFee' : IDL.Nat,
});
export const EventType = IDL.Variant({
  'webinar' : IDL.Null,
  'nutritionTour' : IDL.Null,
  'popupClinic' : IDL.Null,
});
export const CommunityEvent = IDL.Record({
  'id' : IDL.Nat,
  'organizer' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'dateTime' : IDL.Text,
  'location' : IDL.Text,
  'eventType' : EventType,
});
export const Hospital = IDL.Record({
  'id' : IDL.Nat,
  'erWaitMinutes' : IDL.Nat,
  'featuredDepartment' : IDL.Text,
  'departments' : IDL.Vec(IDL.Text),
  'isSponsored' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'address' : IDL.Text,
  'rating' : IDL.Nat,
  'reviewCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'associatedId' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func([Review], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignDoctorOwner' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'assignHospitalOwner' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'bookAppointment' : IDL.Func([Appointment], [IDL.Nat], []),
  'createDoctorProfile' : IDL.Func([DoctorProfile], [IDL.Nat], []),
  'createEvent' : IDL.Func([CommunityEvent], [IDL.Nat], []),
  'createHospital' : IDL.Func([Hospital], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDoctor' : IDL.Func([IDL.Nat], [DoctorProfile], ['query']),
  'getDoctorAppointments' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getDoctorsBySpecialty' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DoctorProfile)],
      ['query'],
    ),
  'getEvent' : IDL.Func([IDL.Nat], [CommunityEvent], ['query']),
  'getEventsByType' : IDL.Func(
      [EventType],
      [IDL.Vec(CommunityEvent)],
      ['query'],
    ),
  'getHospital' : IDL.Func([IDL.Nat], [Hospital], ['query']),
  'getHospitalsByDepartment' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Hospital)],
      ['query'],
    ),
  'getMatchingSpecialties' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getPatientAppointments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getReviewsByTarget' : IDL.Func(
      [IDL.Nat, ReviewTargetType],
      [IDL.Vec(Review)],
      ['query'],
    ),
  'getTopRatedDoctors' : IDL.Func([], [IDL.Vec(DoctorProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchDoctors' : IDL.Func([IDL.Text], [IDL.Vec(DoctorProfile)], ['query']),
  'searchHospitals' : IDL.Func([IDL.Text], [IDL.Vec(Hospital)], ['query']),
  'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
  'updateDoctorProfile' : IDL.Func([IDL.Nat, DoctorProfile], [], []),
  'updateErWaitTime' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateHospital' : IDL.Func([IDL.Nat, Hospital], [], []),
  'verifyDoctor' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ReviewTargetType = IDL.Variant({
    'hospital' : IDL.Null,
    'doctor' : IDL.Null,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'authorId' : IDL.Principal,
    'comment' : IDL.Text,
    'timestamp' : IDL.Int,
    'targetType' : ReviewTargetType,
    'rating' : IDL.Nat,
    'targetId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const AppointmentType = IDL.Variant({
    'diagnostic' : IDL.Null,
    'consultation' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : AppointmentStatus,
    'doctorId' : IDL.Nat,
    'patientId' : IDL.Principal,
    'appointmentType' : AppointmentType,
    'hospitalId' : IDL.Nat,
    'notes' : IDL.Text,
    'dateTime' : IDL.Text,
  });
  const DoctorProfile = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'verified' : IDL.Bool,
    'name' : IDL.Text,
    'available' : IDL.Bool,
    'specialty' : IDL.Text,
    'credentials' : IDL.Text,
    'hospitalId' : IDL.Nat,
    'rating' : IDL.Nat,
    'reviewCount' : IDL.Nat,
    'consultationFee' : IDL.Nat,
  });
  const EventType = IDL.Variant({
    'webinar' : IDL.Null,
    'nutritionTour' : IDL.Null,
    'popupClinic' : IDL.Null,
  });
  const CommunityEvent = IDL.Record({
    'id' : IDL.Nat,
    'organizer' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'dateTime' : IDL.Text,
    'location' : IDL.Text,
    'eventType' : EventType,
  });
  const Hospital = IDL.Record({
    'id' : IDL.Nat,
    'erWaitMinutes' : IDL.Nat,
    'featuredDepartment' : IDL.Text,
    'departments' : IDL.Vec(IDL.Text),
    'isSponsored' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'address' : IDL.Text,
    'rating' : IDL.Nat,
    'reviewCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'associatedId' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func([Review], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignDoctorOwner' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'assignHospitalOwner' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'bookAppointment' : IDL.Func([Appointment], [IDL.Nat], []),
    'createDoctorProfile' : IDL.Func([DoctorProfile], [IDL.Nat], []),
    'createEvent' : IDL.Func([CommunityEvent], [IDL.Nat], []),
    'createHospital' : IDL.Func([Hospital], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDoctor' : IDL.Func([IDL.Nat], [DoctorProfile], ['query']),
    'getDoctorAppointments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getDoctorsBySpecialty' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DoctorProfile)],
        ['query'],
      ),
    'getEvent' : IDL.Func([IDL.Nat], [CommunityEvent], ['query']),
    'getEventsByType' : IDL.Func(
        [EventType],
        [IDL.Vec(CommunityEvent)],
        ['query'],
      ),
    'getHospital' : IDL.Func([IDL.Nat], [Hospital], ['query']),
    'getHospitalsByDepartment' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Hospital)],
        ['query'],
      ),
    'getMatchingSpecialties' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getPatientAppointments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getReviewsByTarget' : IDL.Func(
        [IDL.Nat, ReviewTargetType],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getTopRatedDoctors' : IDL.Func([], [IDL.Vec(DoctorProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchDoctors' : IDL.Func([IDL.Text], [IDL.Vec(DoctorProfile)], ['query']),
    'searchHospitals' : IDL.Func([IDL.Text], [IDL.Vec(Hospital)], ['query']),
    'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
    'updateDoctorProfile' : IDL.Func([IDL.Nat, DoctorProfile], [], []),
    'updateErWaitTime' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateHospital' : IDL.Func([IDL.Nat, Hospital], [], []),
    'verifyDoctor' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };