/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Review {
    id: bigint;
    authorId: Principal;
    comment: string;
    timestamp: bigint;
    targetType: ReviewTargetType;
    rating: bigint;
    targetId: bigint;
}
export interface CommunityEvent {
    id: bigint;
    organizer: string;
    title: string;
    description: string;
    dateTime: string;
    location: string;
    eventType: EventType;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DoctorProfile {
    id: bigint;
    bio: string;
    verified: boolean;
    name: string;
    available: boolean;
    specialty: string;
    credentials: string;
    hospitalId: bigint;
    rating: bigint;
    reviewCount: bigint;
    consultationFee: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Hospital {
    id: bigint;
    erWaitMinutes: bigint;
    featuredDepartment: string;
    departments: Array<string>;
    isSponsored: boolean;
    name: string;
    description: string;
    address: string;
    rating: bigint;
    reviewCount: bigint;
}
export interface Appointment {
    id: bigint;
    status: AppointmentStatus;
    doctorId: bigint;
    patientId: Principal;
    appointmentType: AppointmentType;
    hospitalId: bigint;
    notes: string;
    dateTime: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    role: string;
    associatedId?: bigint;
}
export enum AppointmentStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum AppointmentType {
    diagnostic = "diagnostic",
    consultation = "consultation"
}
export enum EventType {
    webinar = "webinar",
    nutritionTour = "nutritionTour",
    popupClinic = "popupClinic"
}
export enum ReviewTargetType {
    hospital = "hospital",
    doctor = "doctor"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addReview(review: Review): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignDoctorOwner(doctorId: bigint, owner: Principal): Promise<void>;
    assignHospitalOwner(hospitalId: bigint, owner: Principal): Promise<void>;
    bookAppointment(appointment: Appointment): Promise<bigint>;
    createDoctorProfile(profile: DoctorProfile): Promise<bigint>;
    createEvent(event: CommunityEvent): Promise<bigint>;
    createHospital(hospital: Hospital): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDoctor(id: bigint): Promise<DoctorProfile>;
    getDoctorAppointments(doctorId: bigint): Promise<Array<Appointment>>;
    getDoctorsBySpecialty(specialty: string): Promise<Array<DoctorProfile>>;
    getEvent(id: bigint): Promise<CommunityEvent>;
    getEventsByType(eventType: EventType): Promise<Array<CommunityEvent>>;
    getHospital(id: bigint): Promise<Hospital>;
    getHospitalsByDepartment(department: string): Promise<Array<Hospital>>;
    getMatchingSpecialties(symptom: string): Promise<Array<string>>;
    getPatientAppointments(patientId: Principal): Promise<Array<Appointment>>;
    getReviewsByTarget(targetId: bigint, targetType: ReviewTargetType): Promise<Array<Review>>;
    getTopRatedDoctors(): Promise<Array<DoctorProfile>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchDoctors(searchTerm: string): Promise<Array<DoctorProfile>>;
    searchHospitals(searchTerm: string): Promise<Array<Hospital>>;
    updateAppointmentStatus(id: bigint, status: AppointmentStatus): Promise<void>;
    updateDoctorProfile(id: bigint, profile: DoctorProfile): Promise<void>;
    updateErWaitTime(id: bigint, waitTime: bigint): Promise<void>;
    updateHospital(id: bigint, hospital: Hospital): Promise<void>;
    verifyDoctor(id: bigint): Promise<void>;
}
import type { Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, AppointmentType as _AppointmentType, CommunityEvent as _CommunityEvent, EventType as _EventType, Review as _Review, ReviewTargetType as _ReviewTargetType, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addReview(arg0: Review): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(to_candid_Review_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(to_candid_Review_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignDoctorOwner(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignDoctorOwner(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignDoctorOwner(arg0, arg1);
            return result;
        }
    }
    async assignHospitalOwner(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignHospitalOwner(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignHospitalOwner(arg0, arg1);
            return result;
        }
    }
    async bookAppointment(arg0: Appointment): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(to_candid_Appointment_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(to_candid_Appointment_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createDoctorProfile(arg0: DoctorProfile): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDoctorProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDoctorProfile(arg0);
            return result;
        }
    }
    async createEvent(arg0: CommunityEvent): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(to_candid_CommunityEvent_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(to_candid_CommunityEvent_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createHospital(arg0: Hospital): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createHospital(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHospital(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctor(arg0: bigint): Promise<DoctorProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctor(arg0);
            return result;
        }
    }
    async getDoctorAppointments(arg0: bigint): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorAppointments(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorAppointments(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctorsBySpecialty(arg0: string): Promise<Array<DoctorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorsBySpecialty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorsBySpecialty(arg0);
            return result;
        }
    }
    async getEvent(arg0: bigint): Promise<CommunityEvent> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_CommunityEvent_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_CommunityEvent_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventsByType(arg0: EventType): Promise<Array<CommunityEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsByType(to_candid_EventType_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsByType(to_candid_EventType_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHospital(arg0: bigint): Promise<Hospital> {
        if (this.processError) {
            try {
                const result = await this.actor.getHospital(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHospital(arg0);
            return result;
        }
    }
    async getHospitalsByDepartment(arg0: string): Promise<Array<Hospital>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHospitalsByDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHospitalsByDepartment(arg0);
            return result;
        }
    }
    async getMatchingSpecialties(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchingSpecialties(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchingSpecialties(arg0);
            return result;
        }
    }
    async getPatientAppointments(arg0: Principal): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientAppointments(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientAppointments(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewsByTarget(arg0: bigint, arg1: ReviewTargetType): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsByTarget(arg0, to_candid_ReviewTargetType_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsByTarget(arg0, to_candid_ReviewTargetType_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopRatedDoctors(): Promise<Array<DoctorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopRatedDoctors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopRatedDoctors();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchDoctors(arg0: string): Promise<Array<DoctorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDoctors(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDoctors(arg0);
            return result;
        }
    }
    async searchHospitals(arg0: string): Promise<Array<Hospital>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchHospitals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchHospitals(arg0);
            return result;
        }
    }
    async updateAppointmentStatus(arg0: bigint, arg1: AppointmentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointmentStatus(arg0, to_candid_AppointmentStatus_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointmentStatus(arg0, to_candid_AppointmentStatus_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateDoctorProfile(arg0: bigint, arg1: DoctorProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDoctorProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDoctorProfile(arg0, arg1);
            return result;
        }
    }
    async updateErWaitTime(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateErWaitTime(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateErWaitTime(arg0, arg1);
            return result;
        }
    }
    async updateHospital(arg0: bigint, arg1: Hospital): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHospital(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHospital(arg0, arg1);
            return result;
        }
    }
    async verifyDoctor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyDoctor(arg0);
            return result;
        }
    }
}
function from_candid_AppointmentStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_AppointmentType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentType): AppointmentType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_CommunityEvent_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommunityEvent): CommunityEvent {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_EventType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewTargetType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewTargetType): ReviewTargetType {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    associatedId: [] | [bigint];
}): {
    name: string;
    role: string;
    associatedId?: bigint;
} {
    return {
        name: value.name,
        role: value.role,
        associatedId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.associatedId))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AppointmentStatus;
    doctorId: bigint;
    patientId: Principal;
    appointmentType: _AppointmentType;
    hospitalId: bigint;
    notes: string;
    dateTime: string;
}): {
    id: bigint;
    status: AppointmentStatus;
    doctorId: bigint;
    patientId: Principal;
    appointmentType: AppointmentType;
    hospitalId: bigint;
    notes: string;
    dateTime: string;
} {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n32(_uploadFile, _downloadFile, value.status),
        doctorId: value.doctorId,
        patientId: value.patientId,
        appointmentType: from_candid_AppointmentType_n34(_uploadFile, _downloadFile, value.appointmentType),
        hospitalId: value.hospitalId,
        notes: value.notes,
        dateTime: value.dateTime
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    organizer: string;
    title: string;
    description: string;
    dateTime: string;
    location: string;
    eventType: _EventType;
}): {
    id: bigint;
    organizer: string;
    title: string;
    description: string;
    dateTime: string;
    location: string;
    eventType: EventType;
} {
    return {
        id: value.id,
        organizer: value.organizer,
        title: value.title,
        description: value.description,
        dateTime: value.dateTime,
        location: value.location,
        eventType: from_candid_EventType_n38(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    authorId: Principal;
    comment: string;
    timestamp: bigint;
    targetType: _ReviewTargetType;
    rating: bigint;
    targetId: bigint;
}): {
    id: bigint;
    authorId: Principal;
    comment: string;
    timestamp: bigint;
    targetType: ReviewTargetType;
    rating: bigint;
    targetId: bigint;
} {
    return {
        id: value.id,
        authorId: value.authorId,
        comment: value.comment,
        timestamp: value.timestamp,
        targetType: from_candid_ReviewTargetType_n44(_uploadFile, _downloadFile, value.targetType),
        rating: value.rating,
        targetId: value.targetId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): AppointmentStatus {
    return "cancelled" in value ? AppointmentStatus.cancelled : "pending" in value ? AppointmentStatus.pending : "completed" in value ? AppointmentStatus.completed : "confirmed" in value ? AppointmentStatus.confirmed : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    diagnostic: null;
} | {
    consultation: null;
}): AppointmentType {
    return "diagnostic" in value ? AppointmentType.diagnostic : "consultation" in value ? AppointmentType.consultation : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    webinar: null;
} | {
    nutritionTour: null;
} | {
    popupClinic: null;
}): EventType {
    return "webinar" in value ? EventType.webinar : "nutritionTour" in value ? EventType.nutritionTour : "popupClinic" in value ? EventType.popupClinic : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hospital: null;
} | {
    doctor: null;
}): ReviewTargetType {
    return "hospital" in value ? ReviewTargetType.hospital : "doctor" in value ? ReviewTargetType.doctor : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommunityEvent>): Array<CommunityEvent> {
    return value.map((x)=>from_candid_CommunityEvent_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n42(_uploadFile, _downloadFile, x));
}
function to_candid_AppointmentStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): _AppointmentStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_AppointmentType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentType): _AppointmentType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Appointment_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Appointment): _Appointment {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_CommunityEvent_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommunityEvent): _CommunityEvent {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_EventType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): _EventType {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_ReviewTargetType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewTargetType): _ReviewTargetType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Review_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Review): _Review {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: AppointmentStatus;
    doctorId: bigint;
    patientId: Principal;
    appointmentType: AppointmentType;
    hospitalId: bigint;
    notes: string;
    dateTime: string;
}): {
    id: bigint;
    status: _AppointmentStatus;
    doctorId: bigint;
    patientId: Principal;
    appointmentType: _AppointmentType;
    hospitalId: bigint;
    notes: string;
    dateTime: string;
} {
    return {
        id: value.id,
        status: to_candid_AppointmentStatus_n16(_uploadFile, _downloadFile, value.status),
        doctorId: value.doctorId,
        patientId: value.patientId,
        appointmentType: to_candid_AppointmentType_n18(_uploadFile, _downloadFile, value.appointmentType),
        hospitalId: value.hospitalId,
        notes: value.notes,
        dateTime: value.dateTime
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    organizer: string;
    title: string;
    description: string;
    dateTime: string;
    location: string;
    eventType: EventType;
}): {
    id: bigint;
    organizer: string;
    title: string;
    description: string;
    dateTime: string;
    location: string;
    eventType: _EventType;
} {
    return {
        id: value.id,
        organizer: value.organizer,
        title: value.title,
        description: value.description,
        dateTime: value.dateTime,
        location: value.location,
        eventType: to_candid_EventType_n22(_uploadFile, _downloadFile, value.eventType)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    associatedId?: bigint;
}): {
    name: string;
    role: string;
    associatedId: [] | [bigint];
} {
    return {
        name: value.name,
        role: value.role,
        associatedId: value.associatedId ? candid_some(value.associatedId) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    authorId: Principal;
    comment: string;
    timestamp: bigint;
    targetType: ReviewTargetType;
    rating: bigint;
    targetId: bigint;
}): {
    id: bigint;
    authorId: Principal;
    comment: string;
    timestamp: bigint;
    targetType: _ReviewTargetType;
    rating: bigint;
    targetId: bigint;
} {
    return {
        id: value.id,
        authorId: value.authorId,
        comment: value.comment,
        timestamp: value.timestamp,
        targetType: to_candid_ReviewTargetType_n10(_uploadFile, _downloadFile, value.targetType),
        rating: value.rating,
        targetId: value.targetId
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewTargetType): {
    hospital: null;
} | {
    doctor: null;
} {
    return value == ReviewTargetType.hospital ? {
        hospital: null
    } : value == ReviewTargetType.doctor ? {
        doctor: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == AppointmentStatus.cancelled ? {
        cancelled: null
    } : value == AppointmentStatus.pending ? {
        pending: null
    } : value == AppointmentStatus.completed ? {
        completed: null
    } : value == AppointmentStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentType): {
    diagnostic: null;
} | {
    consultation: null;
} {
    return value == AppointmentType.diagnostic ? {
        diagnostic: null
    } : value == AppointmentType.consultation ? {
        consultation: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): {
    webinar: null;
} | {
    nutritionTour: null;
} | {
    popupClinic: null;
} {
    return value == EventType.webinar ? {
        webinar: null
    } : value == EventType.nutritionTour ? {
        nutritionTour: null
    } : value == EventType.popupClinic ? {
        popupClinic: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
